### ISSUE TITLE
Suggestion of tutorial improvement

### ISSUE THREAD

**Issue by throwaway29292** [corpnewt/UnPlugged#1]
I suggest making a slight modification to the tutorial.

macOS Sonoma 14.1.1 recovery image doesn't seem to be able to mount NTFS or exfat partitions. Not even disk utility formatted exfat gets mounted. I suggest formatting it as HFS+ and using Paragon HFS+ for Windows to copy the InstallAssistant.dmg file.

This worked just fine to install the macOS without needing an internet connection.

And BTW: Thank you so much for this tool. I believe it should be the new preferred way to install macOS as it's faster than using the online install and also faster than using macOS VM to create install USB (Which was always extremely slow for me)

**Comment by corpnewt** [comment]
Hmmm - that is concerning.  I just tested Sonoma here and I was unable to mount any NTFS, FAT32, or ExFAT partitions.  Seems Apple keeps tightening their grip on what we can do in the installer.  Big Sur and prior (IIRC) were able to mount multiple NTFS partitions.  Monterey and newer allowed one or 0, which is why I suggested ExFAT in the instructions.

I would prefer if there was a free (and open source, if possible) way to work around this issue.  I may do some other testing and digging around before settling on an approach, but I appreciate the info.

-CorpNewt

**Comment by corpnewt** [comment]
I'm not sure if the installer would launch properly - but that's likely the most sane approach for Sonoma currently.  If you use the BaseSystem.dmg|.chunklist for Ventura and dmg boot that via OpenCore, then place the BaseSystem.dmg and InstallAssistant.pkg in an ExFAT partition next to the UnPlugged.command - you should be able to mount that other BaseSystem.dmg and UnPlugged should be able to find the `Install macOS Sonoma.app` from within.

It's a bit of a hassle - but it *should* work alright.  It's probably also worth checking if the `Install macOS Ventura.app` shell could install the Sonoma InstallAssistant.pkg info - but I would imagine there are version checks that prevent mismatching.

I'll have to do some more digginga nd see what makes the most sense.  I would prefer to avoid altering the BaseSystem.dmg - and Hackintoshes likely don't have a ton of support left, so if this *just* needs to accommodate Sonoma and maybe one more release, using an older recovery env may be the way to go.

-CorpNewt

**Comment by corpnewt** [comment]
I just tested with the following:

16GB USB drive formatted with 2 partitions using an MBR partition table:
1. 800MB FAT32 partition containing my EFI and the com.apple.recovery.boot folder with Ventura's BaseSystem.dmg|.chunklist
2. The remaining 15+GB ExFAT partition containing Sonoma's BaseSystem.dmg, InstallAssistant.pkg, and UnPlugged.command

The recovery environment auto-mounted both the FAT32 and ExFAT volumes - and I was able to mount the BaseSystem.dmg via `hdiutil attach /Volumes/UnPlugged/BaseSystem.dmg` without issue.  I started UnPlugged.command and it was able to find both the `Install macOS Ventura.app` from the recovery env, and the `Install macOS Sonoma.app` from the mounted BaseSystem.dmg.  This seems like the most appropriate way to move forward with this imo.

-CorpNewt

**Comment by corpnewt** [comment]
Likely easier for a first run - but if you set up multiple machines, the trial may expire.  It also requires downloading and installing extra software - which I'd prefer to avoid.  Depending on reception, I may add a note stating that using third party HFS+ software can work around the need for Ventura recovery if installing Sonoma.  We'll see how it goes.

Regardless, I think for the time being, this issue is resolved - so I'll go ahead and close it.  Thanks for bringing it to my attention.

-CorpNewt
